version: "2"

services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: dapphero-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dapphero
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - back-tier

volumes:
  pgdata:

networks:
  back-tier:
    driver: bridge